---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.nodejs
    - role: geerlingguy.postgresql
    - role: pmoscode.wikijs

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
      changed_when: false

    - name: Install crontab
      apt:
        name: cron
        state: present
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

  vars:
    postgresql_databases:
      - name: wiki
    postgresql_users:
      - name: wikijs
        password: wikijsrocks
    nodejs_install_npm_user: root
